DELETE FROM PROPOSAL_ANTICIPATION ;
DELETE FROM LESSON ;
DELETE FROM CLASS_COURSE ;
DELETE FROM SUBJECT ;
DELETE FROM LECTURER ;
DELETE FROM ATTENDANCE ;
DELETE FROM STUDENT ;
DELETE FROM DEPARTMENT ;