
--BASE SQL INSERTS

-- BEGIN INSERTS STUDENTS

INSERT INTO "STUDENT" (ID,NAME) VALUES (1,'Dieter Salas');
INSERT INTO "STUDENT" (ID,NAME) VALUES (2,'Hamilton Buchanan');
INSERT INTO "STUDENT" (ID,NAME) VALUES (3,'Nero Gardner');
INSERT INTO "STUDENT" (ID,NAME) VALUES (4,'Meredith Nixon');
INSERT INTO "STUDENT" (ID,NAME) VALUES (5,'Stacey Moore');
INSERT INTO "STUDENT" (ID,NAME) VALUES (6,'Bert Ewing');
INSERT INTO "STUDENT" (ID,NAME) VALUES (7,'Aspen Hahn');
INSERT INTO "STUDENT" (ID,NAME) VALUES (8,'Lael Carlson');
INSERT INTO "STUDENT" (ID,NAME) VALUES (9,'Vivian Vinson');
INSERT INTO "STUDENT" (ID,NAME) VALUES (10,'Leandra Lang');
INSERT INTO "STUDENT" (ID,NAME) VALUES (11,'Hyatt Glover');
INSERT INTO "STUDENT" (ID,NAME) VALUES (12,'Kennan Nixon');
INSERT INTO "STUDENT" (ID,NAME) VALUES (13,'Ifeoma Shelton');
INSERT INTO "STUDENT" (ID,NAME) VALUES (14,'Brenden Lewis');
INSERT INTO "STUDENT" (ID,NAME) VALUES (15,'Thor Buchanan');
INSERT INTO "STUDENT" (ID,NAME) VALUES (16,'Raya Avery');
INSERT INTO "STUDENT" (ID,NAME) VALUES (17,'Ferris Obrien');
INSERT INTO "STUDENT" (ID,NAME) VALUES (18,'Rosalyn Barry');
INSERT INTO "STUDENT" (ID,NAME) VALUES (19,'Tashya Bird');
INSERT INTO "STUDENT" (ID,NAME) VALUES (20,'Lester Banks');
INSERT INTO "STUDENT" (ID,NAME) VALUES (21,'Zelenia Farrell');
INSERT INTO "STUDENT" (ID,NAME) VALUES (22,'Nayda Forbes');
INSERT INTO "STUDENT" (ID,NAME) VALUES (23,'Micah Rose');
INSERT INTO "STUDENT" (ID,NAME) VALUES (24,'Amanda Hartman');
INSERT INTO "STUDENT" (ID,NAME) VALUES (25,'Xerxes Murphy');
INSERT INTO "STUDENT" (ID,NAME) VALUES (26,'Casey Stein');
INSERT INTO "STUDENT" (ID,NAME) VALUES (27,'Blaine Stout');
INSERT INTO "STUDENT" (ID,NAME) VALUES (28,'Kylie Gillespie');
INSERT INTO "STUDENT" (ID,NAME) VALUES (29,'Wallace Jackson');
INSERT INTO "STUDENT" (ID,NAME) VALUES (30,'Isadora Pacheco');
INSERT INTO "STUDENT" (ID,NAME) VALUES (31,'Kyle Huff');
INSERT INTO "STUDENT" (ID,NAME) VALUES (32,'Marshall Rutledge');
INSERT INTO "STUDENT" (ID,NAME) VALUES (33,'Patrick Griffin');
INSERT INTO "STUDENT" (ID,NAME) VALUES (34,'Chancellor Anderson');
INSERT INTO "STUDENT" (ID,NAME) VALUES (35,'Brynne England');
INSERT INTO "STUDENT" (ID,NAME) VALUES (36,'Josiah Miranda');
INSERT INTO "STUDENT" (ID,NAME) VALUES (37,'Jorden Mcneil');
INSERT INTO "STUDENT" (ID,NAME) VALUES (38,'Charissa Contreras');
INSERT INTO "STUDENT" (ID,NAME) VALUES (39,'Ronan Wiggins');
INSERT INTO "STUDENT" (ID,NAME) VALUES (40,'Fuller Gay');
INSERT INTO "STUDENT" (ID,NAME) VALUES (41,'Wynter Snider');
INSERT INTO "STUDENT" (ID,NAME) VALUES (42,'Yardley Bradford');
INSERT INTO "STUDENT" (ID,NAME) VALUES (43,'Madaline Owens');
INSERT INTO "STUDENT" (ID,NAME) VALUES (44,'Rae Hess');
INSERT INTO "STUDENT" (ID,NAME) VALUES (45,'Juliet Faulkner');
INSERT INTO "STUDENT" (ID,NAME) VALUES (46,'Aileen Marquez');
INSERT INTO "STUDENT" (ID,NAME) VALUES (47,'Simon Briggs');
INSERT INTO "STUDENT" (ID,NAME) VALUES (48,'Kibo Jacobs');
INSERT INTO "STUDENT" (ID,NAME) VALUES (49,'Leila Calhoun');
INSERT INTO "STUDENT" (ID,NAME) VALUES (50,'Angela Buchanan');

-- END INSERTS STUDENTS

-- BEGIN ATTENDANCE STUDENTS LIST

INSERT INTO "ATTENDANCE_STUDENT" (ID,NOTE) VALUES (100,'pharetra nibh. Aliquam ornare, libero at');
INSERT INTO "ATTENDANCE_STUDENT" (ID,NOTE) VALUES (101,'Vivamus non lorem vitae odio sagittis semper. Nam');
INSERT INTO "ATTENDANCE_STUDENT" (ID,NOTE) VALUES (102,'molestie orci tincidunt adipiscing. Mauris molestie pharetra');
INSERT INTO "ATTENDANCE_STUDENT" (ID,NOTE) VALUES (103,'pharetra, felis eget varius ultrices,');
INSERT INTO "ATTENDANCE_STUDENT" (ID,NOTE) VALUES (104,'tristique neque venenatis lacus. Etiam');
INSERT INTO "ATTENDANCE_STUDENT" (ID,NOTE) VALUES (105,'dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas');

-- END ATTENDANCE STUDENTS LIST

-- BEGIN ATTENDANCE STUDENT

INSERT INTO ATTENDANCE VALUES('1','False',103,14);
INSERT INTO ATTENDANCE VALUES('2','False',103,29);
INSERT INTO ATTENDANCE VALUES('3','True',101,32);
INSERT INTO ATTENDANCE VALUES('4','False',105,32);
INSERT INTO ATTENDANCE VALUES('5','False',102,14);
INSERT INTO ATTENDANCE VALUES('6','False',101,1);
INSERT INTO ATTENDANCE VALUES('7','False',104,31);
INSERT INTO ATTENDANCE VALUES('8','False',102,7);
INSERT INTO ATTENDANCE VALUES('9','False',105,23);
INSERT INTO ATTENDANCE VALUES('10','True',104,16);
INSERT INTO ATTENDANCE VALUES('11','True',105,38);
INSERT INTO ATTENDANCE VALUES('12','True',100,23);
INSERT INTO ATTENDANCE VALUES('13','True',101,8);
INSERT INTO ATTENDANCE VALUES('14','True',105,41);
INSERT INTO ATTENDANCE VALUES('15','True',104,48);
INSERT INTO ATTENDANCE VALUES('16','True',102,7);
INSERT INTO ATTENDANCE VALUES('17','True',103,20);
INSERT INTO ATTENDANCE VALUES('18','True',104,48);
INSERT INTO ATTENDANCE VALUES('19','True',103,6);
INSERT INTO ATTENDANCE VALUES('20','True',103,33);
INSERT INTO ATTENDANCE VALUES('21','True',102,29);
INSERT INTO ATTENDANCE VALUES('22','True',104,49);
INSERT INTO ATTENDANCE VALUES('23','True',103,19);
INSERT INTO ATTENDANCE VALUES('24','True',100,49);
INSERT INTO ATTENDANCE VALUES('25','True',105,41);
INSERT INTO ATTENDANCE VALUES('26','True',100,34);
INSERT INTO ATTENDANCE VALUES('27','True',102,27);
INSERT INTO ATTENDANCE VALUES('28','True',102,6);
INSERT INTO ATTENDANCE VALUES('29','True',101,4);
INSERT INTO ATTENDANCE VALUES('30','True',105,28);
INSERT INTO ATTENDANCE VALUES('31','True',102,33);
INSERT INTO ATTENDANCE VALUES('32','True',104,25);
INSERT INTO ATTENDANCE VALUES('33','True',104,1);
INSERT INTO ATTENDANCE VALUES('34','True',101,35);
INSERT INTO ATTENDANCE VALUES('35','True',105,22);
INSERT INTO ATTENDANCE VALUES('36','True',101,44);
INSERT INTO ATTENDANCE VALUES('37','True',100,23);
INSERT INTO ATTENDANCE VALUES('38','True',105,10);
INSERT INTO ATTENDANCE VALUES('39','True',104,1);
INSERT INTO ATTENDANCE VALUES('40','True',102,25);
INSERT INTO ATTENDANCE VALUES('41','True',100,35);
INSERT INTO ATTENDANCE VALUES('42','True',102,34);
INSERT INTO ATTENDANCE VALUES('43','True',102,5);
INSERT INTO ATTENDANCE VALUES('44','True',103,16);
INSERT INTO ATTENDANCE VALUES('45','True',101,9);
INSERT INTO ATTENDANCE VALUES('46','True',103,22);
INSERT INTO ATTENDANCE VALUES('47','True',103,5);
INSERT INTO ATTENDANCE VALUES('48','True',104,44);
INSERT INTO ATTENDANCE VALUES('49','True',105,24);
INSERT INTO ATTENDANCE VALUES('50','True',102,1);

-- END ATTENDANCE STUDENT

-- BEGIN LECTURER

INSERT INTO "LECTURER" (ID,NAME) VALUES (123456,'Joe');
INSERT INTO "LECTURER" (ID,NAME) VALUES (12095,'Chantale J. Russo');
INSERT INTO "LECTURER" (ID,NAME) VALUES (43251,'Devin H. Marquez');
INSERT INTO "LECTURER" (ID,NAME) VALUES (30652,'Orlando H. Webster');
INSERT INTO "LECTURER" (ID,NAME) VALUES (23198,'Alisa G. Webb');
INSERT INTO "LECTURER" (ID,NAME) VALUES (17367,'Nero V. Mcgee');
INSERT INTO "LECTURER" (ID,NAME) VALUES (30621,'Octavia I. Becker');
INSERT INTO "LECTURER" (ID,NAME) VALUES (10295,'Lysandra X. Rivera');
INSERT INTO "LECTURER" (ID,NAME) VALUES (22390,'Kermit O. Diaz');
INSERT INTO "LECTURER" (ID,NAME) VALUES (28649,'Orson I. Carrillo');
INSERT INTO "LECTURER" (ID,NAME) VALUES (42513,'Janna D. Benton');
INSERT INTO "LECTURER" (ID,NAME) VALUES (40768,'Audra R. Cleveland');
INSERT INTO "LECTURER" (ID,NAME) VALUES (36002,'Stacy O. Chen');
INSERT INTO "LECTURER" (ID,NAME) VALUES (23280,'Louis L. Olsen');
-- END LECTURER

-- BEGIN SUBJECT
INSERT INTO SUBJECT ( ID , NAME ) VALUES (3, 'Engenharia da Computação');
-- END SUBJECT

-- BEGIN CLASS_COURSE
INSERT INTO CLASS_COURSE ( ID , LECTURER_ID , SUBJECT_ID)  VALUES  (28, 123456, 3);
-- END CLASS_COURSE

-- BEGIN LESSON
INSERT INTO LESSON (ID ,CONTENT ,DATE ,NUMBER_CLASSES ,ATTENDANCE_STUDENT_ID ,CLASS_COURSE_ID) VALUES (75, 'Lista Encadeada', '2018-10-5', 2, 100, 28);
-- END LESSON

-- BEGIN PROPOSAL_ANTICIPATION
INSERT INTO PROPOSAL_ANTICIPATION  ( ID , MODALITIE , NEXT_DATE , NUMBER_CLASSES ,DESCRIPTION_REASON , REASON_BY, LESSON_ID  ) VALUES (1,'PRESENCIAL','2018-9-2',3,'Viagem',  'PREVISTO', 75);
-- END PROPOSAL_ANTICIPATION

-- BEGIN DEPARTMENT
INSERT INTO DEPARTMENT  (id, name) VALUES (1, 'Computação')
-- END DEPARTMENT







